export const dummyProperties = [{
    id: "1",
    title: "Modern Luxury Apartment",
    location: "Manhatten, New York",
    price:2500,
    type:"Apartment",
    status:"rent",
    bedrooms:4,
    bathrooms:3,
    area:2200,
    featured:true,
    image:"/images/image1.jpg",
    description:"A stunning luxury apartment with modern interiors, spacious rooms, and"
},
{
    id: "2",
    title: "Contemorary Family Villa",
    location: "Beverly Hills, Los Angeles",
    price:85000,
    type:"Villa",
    status:"sale",
    bedrooms:5,
    bathrooms:4,
    area:4500,
    featured:true,
    image:"/images/image2.jpg",
    description:"Beautiful contemporary villa featuring elegant architecture, large "
},
{
    id: "3",
    title: "Minimalist Smart Home",
    location: "Tokyo, Japan",
    price:4200,
    type:"Smart Home",
    status:"rent",
    bedrooms:3,
    bathrooms:3,
    area:2800,
    featured: false,
    image:"/images/image3.jpg",
    description:"Fully automated smart home with premium finishes, floor-to-ceiling windows"
},
{
    id: "4",
    title: "Elegant Waterfront Duplex",
    location: "Dubai Marina, Dubai",
    price:125000,
    type:"Duplex",
    status:"sale",
    bedrooms:6,
    bathrooms:5,
    area:5200,
    featured:true,
    image:"/images/image4.jpg",
    description:"Luxuray waterfront duplex with private parking, rooftop terrace, and panoramic views"
},
{
    id: "5",
    title: "Urban Studio Apartment",
    location: "Paris, France",
    price:1200,
    type:"Studio",
    status:"rent",
    bedrooms:1,
    bathrooms:1,
    area:850,
    featured: false,
    image:"/images/image5.jpg",
    description:"Compact and stylish studio apartment perfect for young professionals"
},
{
    id: "6",
    title: "Premium Penthouse Suite",
    location: "London, United Kingdom",
    price:250000,
    type:"Penthouse",
    status:"sale",
    bedrooms:5,
    bathrooms:6,
    area:6800,
    featured:true,
    image:"/images/image6.jpg",
    description:"Exclusive penthouse suite with panoramic ocean views"
},
]